# Generated by Django 3.0.2 on 2021-11-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0005_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='em_oferta',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd',
            field=models.FloatField(),
        ),
    ]
