# Generated by Django 3.0.2 on 2021-11-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_auto_20211113_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unid',
            field=models.CharField(choices=[('cx', 'caixa'), ('g', 'grama'), ('gl', 'galão'), ('kg', 'quilo'), ('l', 'litro'), ('ml', 'mililitro'), ('pc', 'pacote'), ('pç', 'peça'), ('unid', 'unidade')], max_length=10),
        ),
    ]
