# Generated by Django 3.0.2 on 2022-05-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0007_auto_20211113_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='em_oferta',
            name='fonte',
            field=models.CharField(choices=[('Panfleto', 'Panfleto'), ('Funcionário', 'Funcionário'), ('Cliente', 'Cliente')], default='Panfleto', max_length=15),
        ),
    ]
